version: git-{branch}-{build}
configuration: Debug
platform:
- x86
- x64
build:
  project: shell/reicast.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: mkdir artifacts
  - cmd: set PLATFORM2=%PLATFORM:x86=Win32%
  - cmd: move WorkDir\reicast_%PLATFORM2%_Slow.exe artifacts/reicast-win-%PLATFORM%-%APPVEYOR_REPO_COMMIT%-slow.exe

artifacts:
  - path: artifacts
    name: reicast-win-$(platform)-slow
