name: reicast
version: git
summary: Reicast
description: |
  Reicast is a Sega Dreamcast emulator. It is designed to run dreamcast games
  and homebrew in x86, x64 and aarch64 based platforms.
grade: devel
icon: shell/linux/reicast.png
confinement: strict

apps:
  reicast:
    command:  desktop-launch $SNAP/reicast
    plugs: [home, alsa, pulseaudio, opengl, x11, joystick, unity7]

parts:
  reicast:
    source: .
    source-subdir: shell/linux
    plugin: make
    make-parameters: [ PREFIX= ]
    build-packages:
      - build-essential
      - libasound2-dev
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - mesa-common-dev
      - pkg-config
    after: [desktop-gtk2]
