name: Nintendo Switch CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    strategy:
      matrix:
        config:
          - {name: standalone, destDir: switch}
          - {name: libretro, cmakeArgs: -DLIBRETRO=ON}

    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install awscli

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: CMake
        run: |
          $DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.config.cmakeArgs }}
          cmake --build build --config Release --parallel 2

      - uses: actions/upload-artifact@v2
        with:
          name: flycast-switch-${{ matrix.config.name }}
          path: build/artifact

      - name: Package app
        run: |
          cd build/artifact
          zip flycast.nro.zip flycast.nro
          rm -f flycast.nro
        if: matrix.config.destDir != ''

      - name: Set up git vars
        run: |
          echo GIT_BUILD=`git describe --all --always | sed 's/remotes\/origin/heads/'`-$GITHUB_SHA >> $GITHUB_ENV
        shell: bash

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAJOZQS4H2PHQWYFCA
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: us-east-2
        if: github.repository == 'flyinghead/flycast' && github.event_name == 'push' && matrix.config.destDir != ''

      - name: Upload to S3
        run: aws s3 sync build/artifact s3://flycast-builds/${{ matrix.config.destDir }}/${{ env.GIT_BUILD }} --acl public-read --follow-symlinks
        if: ${{ steps.aws-credentials.outputs.aws-account-id != '' }}
